static const struct 
{
	char	*extension;
	char	*mime_type;
} 

//http://www.webmaster-toolkit.com/mime-types.shtml
//last did aab

builtin_mime_types[] =  {
	{"3dm",		"x-world/x-3dmf"				},
	{"3dmf",	"x-world/x-3dmf"				},
	{"a",		"application/octet-stream"		},
	{"aab",		"application/x-authorware-bin"	},
	{"ani",		"application/x-navi-animation"	},
	{"arj",		"application/x-arj-compressed"	},
	{"asf",		"video/x-ms-asf"				},
	{"avi",		"video/x-msvideo"				},
	{"bin",		"application/octet-stream"		},
	{"bmp",		"image/bmp"						},
	{"c",		"text/plain"					},
	{"c++",		"text/plain"					},
	{"class",	"application/java"				},
	{"css",		"text/css"						},
	{"doc",		"application/msword"			},
	{"exe",		"application/octet-stream"		},
	{"gif",		"image/gif"						},
	{"gtar",	"application/x-gtar"			},
	{"gz",		"application/x-gunzip"			},
	{"h",		"text/plain"					},
	{"htm",		"text/html"						},
	{"html", 	"text/html"						},
	{"ico",		"image/x-icon"					},
	{"java",	"text/plain"					},
	{"jpe",		"image/jpeg"					},
	{"jpeg",	"mage/jpeg"						},
	{"jpg",		"mage/jpeg"						},
	{"js",		"application/x-javascript"		},
	{"m3u",		"audio/x-mpegurl"				},
	{"mid",		"audio/mid"						},	
	{"midi",	"audio/midi"					},
	{"mod",		"audio/mod"						},
	{"mp2",		"video/mpeg"					},
	{"mp3",		"audio/x-mp3"					},
	{"mpa",		"video/mpeg"					},
	{"mpe",		"video/mpeg"					},
	{"mpeg",	"video/mpeg"					},
	{"mpg",		"video/mpeg"					},
	{"mpp",		"application/vnd.ms-project"	},
	{"mpv2",	"video/mpeg"					},
	{"mp3",		"audio/x-mp3"					},
	{"mov",		"video/quicktime"				},
	{"pdf",		"application/pdf"				},
	{"png",		"image/png"						},
	{"pps",		"application/vnd.ms-powerpoint"	},
	{"ppt",		"application/vnd.ms-powerpoint"	},
	{"qt",		"video/quicktime"				},
	{"ra",		"audio/x-pn-realaudio"			},
	{"ram",		"audio/x-pn-realaudio"			},
	{"rar",		"application/x-arj-compressed"	},
	{"rtf",		"application/rtf"				},
	{"rtx",		"text/richtext"					},
	{"svg",		"image/svg+xml"					},
	{"swf",		"application/x-shockwave-flash"	},
	{"tar",		"application/x-tar"				},
	{"tif",		"image/tiff"					},
	{"tiff",	"image/tiff"					},
	{"txt",		"text/plain"					},
	{"tgz",		"application/x-tar-gz"			},
	{"torrent",	"application/x-bittorrent"		},
	{"txt",		"text/plain"					},
	{"wav",		"audio/wav"						},
	{"wmv",		"video/x-ms-wmv"    			},
	{"xls",		"application/excel"				},
	{"xla",		"application/vnd.ms-excel"		},
	{"xlc",		"application/vnd.ms-excel"		},
	{"xlm",		"application/vnd.ms-excel"		},
	{"xls",		"application/vnd.ms-excel"		},
	{"xlt",		"application/vnd.ms-excel"		},
	{"xlw",		"application$/vnd.ms-excel"		},
	{"xml",		"text/xml"						},
	{"z",		"application/x-compress"		},
	{"zip",		"application/x-zip-compressed"	},
	{NULL,		"application/octect-stream"		}
};
